/****************
    VIEW
*****************/
--단일 VIEW
CREATE VIEW EMP_VIEW
AS
SELECT EMPNO,ENAME,SAL,HIREDATE
FROM EMP
WHERE DEPTNO=10;

SELECT * FROM SYS.USER_VIEWS;

SELECT * FROM (SELECT EMPNO,ENAME,SAL,HIREDATE
                FROM EMP
              WHERE DEPTNO=10);


SELECT EMPNO,ENAME,SAL,HIREDATE FROM EMP_VIEW;

CREATE OR REPLACE VIEW DEPT_VIEW
AS
SELECT DEPTNO NO ,DNAME NAME
FROM DEPT;

DESC DEPT_VIEW;

SELECT * FROM DEPT_VIEW;

CREATE VIEW DEPT_VIEW
AS
SELECT DEPTNO NO,DNAME NAME ,LOC
FROM DEPT;
--SQL 오류: ORA-00955: name is already used by an existing object
CREATE OR REPLACE VIEW DEPT_VIEW
AS
SELECT DEPTNO NO,DNAME NAME ,LOC
FROM DEPT;

--복합VIEW

CREATE OR REPLACE VIEW EMP_DEPT_VIEW
AS
SELECT e.EMPNO,e.ENAME,d.DNAME
FROM EMP e,DEPT d
WHERE e.DEPTNO=d.DEPTNO;

DESC EMP_DEPT_VIEW;
/*
SYS.USER_VIEWS 
*/
SELECT * FROM USER_VIEWS;

SELECT * FROM EMP_DEPT_VIEW;
            
--VIEW DML(INSERT,DELETE,UPDATE)  
CREATE OR REPLACE VIEW EMP_VIEW
AS
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10;

SELECT * FROM EMP_VIEW;

/*
7782	CLARK	  MANAGER	  2450	10
7839	KING	  PRESIDENT	5000	10
7934	MILLER	CLERK	    1300	10
*/
INSERT INTO EMP_VIEW VALUES(9999,'김경호','CLERK',1200,10);
--VIEW의 WHERE 조건을 만족하지않은 행 INSERT
INSERT INTO EMP_VIEW VALUES(9998,'김경미','MANAGER',2400,20);

UPDATE EMP_VIEW SET SAL=7777 WHERE EMPNO=7934;
--VIEW의 WHERE 조건을 만족하지않은 행 UPDATE
UPDATE EMP_VIEW SET SAL=1111 WHERE EMPNO=9998;
UPDATE EMP_VIEW SET SAL=3333 WHERE DEPTNO=20;
--0개 행 이(가) 업데이트되었습니다

DELETE FROM EMP_VIEW WHERE EMPNO=7782;
--VIEW의 WHERE 조건을 만족하지않은 행 DELETE
DELETE FROM EMP_VIEW WHERE DEPTNO=30;
--0개 행 이(가) 삭제되었습니다.
/*
VIEW <<WITH CHECK OPTION>>
*/
CREATE OR REPLACE VIEW EMP_CHECK_VIEW
AS
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP
WHERE DEPTNO=10
WITH CHECK OPTION CONSTRAINT EMP_CHECK_VIEW_CHECK;

INSERT INTO EMP_CHECK_VIEW VALUES(1111,'신명숙','연구원',3000,10);
INSERT INTO EMP_CHECK_VIEW VALUES(2222,'최경녀','CLERK',2000,20);

UPDATE EMP_CHECK_VIEW SET DEPTNO=30 WHERE EMPNO=1111;
--SQL 오류: ORA-01402: view WITH CHECK OPTION where-clause violation


/*
VIEW << WITH READ ONLY >>
*/

CREATE OR REPLACE VIEW EMP_READ_VIEW
AS
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP
WHERE DEPTNO=10
WITH READ ONLY;           
            
INSERT INTO EMP_READ_VIEW VALUES(1234,'KIM','SALES',5000,10);
--SQL 오류: ORA-42399: 
--      cannot perform a DML operation on a read-only view
 
/*
 VIEW << DROP >>
*/
  
DROP VIEW DEPT_VIEW; 

/**********
SEQUENCE
***********/

CREATE SEQUENCE DEPT_SEQ
INCREMENT BY 10
START WITH 100
MAXVALUE 9000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE EMP_EMPNO_SEQ;

/*
시퀀스이름.NEXTVAL
  - 시퀀스의 값을 증가시켜 숫자를 생성한다
  - 첫번째생성되는숫자는 100이다.(START WITH 100) 
시퀀스이름.CURRVAL
  - 시퀀스가 가지고있는 현재숫자값
  - 시퀀스생성후 시퀀스이름.NEXTVAL 이 실행되지않은상태에서는
    사용불가능 
*/
SELECT DEPT_SEQ.CURRVAL FROM DUAL;
/*
 이유:sequence CURRVAL has been selected before sequence NEXTVAL
 해결:select NEXTVAL from the sequence before selecting CURRVAL
*/
SELECT DEPT_SEQ.NEXTVAL FROM DUAL; 

INSERT INTO EMP(EMPNO,ENAME,JOB) 
VALUES(EMP_EMPNO_SEQ.NEXTVAL ,'KIM','SALES');

INSERT INTO EMP(EMPNO,ENAME,JOB) 
VALUES(
  EMP_EMPNO_SEQ.NEXTVAL ,
  'KIM'||EMP_EMPNO_SEQ.CURRVAL,
  'SALES');
  
SELECT * FROM EMP;

-----게시판------  
CREATE TABLE BOARD(
    BOARD_NO NUMBER(5) PRIMARY KEY,
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(400) NOT NULL,
    BOARD_DATE DATE
);  
CREATE SEQUENCE BOARD_NO_SEQ
START WITH 1
NOCACHE;

INSERT INTO BOARD 
VALUES(BOARD_NO_SEQ.NEXTVAL,'게시판제목','게시판내용',SYSDATE);
--주문번호 PK(2016-10-12-1)
SELECT 
  TO_CHAR(SYSDATE,'YYYY-MM-DD')||'-'||BOARD_NO_SEQ.NEXTVAL "주문번호"
FROM DUAL;



SELECT DEPT_SEQ.CURRVAL FROM DUAL;
DROP SEQUENCE DEPT_SEQ;

          
          
          
-- 인덱스(INDEX) -- 색인

CREATE INDEX EMP_ENAME_INX ON EMP(ENAME);
SELECT * FROM USER_INDEXES;
SELECT * FrOM USER_IND_COLUMNS;

DROP INDEX EMP_ENAME_INX;

CREATE INDEX EMP_ENAME_IDX ON EMP(ENAME);


/*
동의어(SYNONYM)
*/

CREATE SYNONYM D_SYN FOR DEPT;
--SQL 오류: ORA-01031: insufficient privileges 권한 없음

-- sys계정에서 scott에게 동의어(synonym)생성권한 부여
GRANT CREATE SYNONYM TO SCOTT;

-- 다시 scott계정으로 복귀


