select * from dept;

update DEPT set DNAME='연구부' where DEPTNO=90;

---------------------------------------------------
--DDL

CREATE TABLE DEPT_2(
  DEPTNO NUMBER(2),
  DNAME VARCHAR2(10),
  LOC VARCHAR2(10));
  
CREATE TABLE SCOTT.DEPT_3(
  DEPTNO NUMBER(2),
  DNAME VARCHAR2(10),
  LOC VARCHAR2(10)
);

--default

CREATE TABLE DEF_TABLE(
  NUM NUMBER(1),
  WRITE_DAY DATE
);
INSERT INTO DEF_TABLE(NUM) VALUES(1);
INSERT INTO DEF_TABLE VALUES(2, SYSDATE);

CREATE TABLE DEF_TABLE2(
  NUM NUMBER(1),
  WRITE_DAY DATE DEFAULT SYSDATE
);

INSERT INTO DEF_TABLE2(NUM) VALUES(1);
INSERT INTO DEF_TABLE2(NUM,WRITE_DAY) VALUES(2,DEFAULT);
SELECT * FROM DEF_TABLE2;



CREATE TABLE DEF_TABLE3(
  NUM NUMBER(1),
  WRITE_DAY DATE DEFAULT TO_DATE('2016/01/01','YYYY/MM/DD')
);
INSERT INTO DEF_TABLE3(NUM)
VALUES(1);

INSERT INTO DEF_TABLE3(NUM,WRITE_DAY)
VALUES(2,DEFAULT);

INSERT INTO DEF_TABLE3(NUM,WRITE_DAY)
VALUES(3,TO_DATE('2016/12/07','YYYY/MM/DD'));

SELECT * FROM DEF_TABLE3;
commit;


--DATA TYPE

--TIMESTAMP
CREATE TABLE NEW_TMP(
  TMP_ID NUMBER,
  W_DAY DATE,
  W_DAY2 TIMESTAMP(9)
); 

INSERT INTO NEW_TMP VALUES(1,SYSDATE,SYSTIMESTAMP);
INSERT INTO NEW_TMP 
VALUES(2,
      TO_DATE('2016/10/10 03:45:45','YYYY/MM/DD HH24:MI:SS'),
      TO_TIMESTAMP('2016/10/10 03:45:45.123456789','YYYY/MM/DD HH24:MI:SS.FF9'));
      
SELECT TMP_ID, 
       TO_CHAR(W_DAY,'YYYY/MM/DD HH24:MI:SS SSSSS'),
       W_DAY2 FROM NEW_TMP;

       
--CTAS(create table as select)
CREATE TABLE DEPTA 
AS 
SELECT * FROM DEPT;

CREATE TABLE DEPTB(NO, NAME)
AS
SELECT DEPTNO, DNAME FROM DEPT;

/*
-- DDL 제약조건
  NOT NULL
  UNIQUE KEY - NULL 여러개는 허용된다.
  PRRMARY KEY
  FOREIGN KEY
  CHECK
*/
--CONSTRAINT(제약조건)
/*
1.NOT NULL
*/
CREATE TABLE SAWON(
  S_NO NUMBER(4),
  S_NAME VARCHAR2(19) NOT NULL,
  S_HIREDATE DATE 
    CONSTRAINT SAWON_S_HIREDATE_NN NOT NULL
);

CREATE TABLE new_Talbe2(
    col1 NUMBER DEFAULT 0,
    col2 VARCHAR2(10) NOT NULL,
    col3 DATE,
    col4 TIMESTAMP,
    
    CONSTRAINT new_Table_UK UNIQUE(col1,col2, col3),
    CONSTRAINT new_Table_PK PRIMARY KEY(col1)
);
DESC USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;

INSERT INTO NEW_TALBE VALUES(null);



DESC SAWON;

DESC USER_CONSTRAINTS;

SELECT CONSTRAINT_NAME,
       CONSTRAINT_TYPE,
       TABLE_NAME 
FROM   USER_CONSTRAINTS;

INSERT INTO SAWON VALUES(1,'길동',SYSDATE);
INSERT INTO SAWON VALUES(2,'길서',NULL);
--SQL 오류: ORA-01400: cannot insert NULL into ("SCOTT"."SAWON"."S_HIREDATE")
INSERT INTO SAWON(S_NO,S_NAME)
VALUES(3,'길남');
--SQL 오류: ORA-01400: cannot insert NULL into ("SCOTT"."SAWON"."S_HIREDATE")
INSERT INTO SAWON(S_NO,S_HIREDATE)
VALUES(4,TO_DATE('2016-10-10'));
--SQL 오류: ORA-01400: cannot insert NULL into ("SCOTT"."SAWON"."S_NAME")
INSERT INTO SAWON(S_NAME,S_HIREDATE)
VALUES('길서',TO_DATE('2016-10-10'));

SELECT * FROM SAWON;

/*
2.UNIQUE
*/
-- column 수준에서 제약조건부여
CREATE TABLE SAWON_2(
  S_NO NUMBER(2),
  S_NAME VARCHAR2(10) NOT NULL,
  S_EMAIL VARCHAR2(20) CONSTRAINT SAWON_2_S_EMAIL_UQ UNIQUE
);

INSERT INTO SAWON_2
VALUES(1,'홍길동','hong@naver.com');

INSERT INTO SAWON_2
VALUES(2,'유관순','hong@naver.com');
--SQL 오류: ORA-00001: unique constraint (SCOTT.SAWON_2_S_EMAIL_UQ) violated

INSERT INTO SAWON_2
VALUES(3,'강감찬',NULL);

INSERT INTO SAWON_2
VALUES(4,'임꺽정',NULL);

SELECT * FROM SAWON_2;
-- table 수준에서 제약조건부여
DROP TABLE SAWON_3;
CREATE TABLE SAWON_3(
  S_NO NUMBER(2),
  S_NAME VARCHAR2(10),
  S_EMAIL VARCHAR2(20), 
  CONSTRAINT SAWON_3_S_EMAIL_UQ UNIQUE(S_EMAIL)
);

INSERT INTO SAWON_3 VALUES(1,'홍길동','hong@naver.com');
--INSERT INTO SAWON_3 VALUES(2,'김길동','hong@naver.com');

CREATE TABLE SAWON_4(
  S_NO NUMBER(2),
  S_NAME VARCHAR2(10),
  S_EMAIL VARCHAR2(20),
  CONSTRAINT SAWON_4_UQ UNIQUE(S_NAME, S_EMAIL)
);

INSERT INTO SAWON_4 VALUES(1, '홍길동', 'abc@naver.com');
INSERT INTO SAWON_4 VALUES(2, '김길동', 'abc@naver.com');
INSERT INTO SAWON_4 VALUES(3, '이길동', 'abc@naver.com');
INSERT INTO SAWON_4 VALUES(4, '이순신', NULL);
INSERT INTO SAWON_4 VALUES(5, '김순신', NULL);
INSERT INTO SAWON_4 VALUES(6, '김순신', NULL); --UNIQUE 제약 조건 때문에 삽입 실패
INSERT INTO SAWON_4 VALUES(7, NULL, NULL);
INSERT INTO SAWON_4 VALUES(8, NULL, NULL);

SELECT * FROM SAWON_4;


/*
3.PRIMARY KEY
*/
DROP TABLE SAWON_6;
CREATE TABLE SAWON_6(
  S_NO NUMBER(2),
  S_NAME VARCHAR2(10),
  S_SAL NUMBER(10,3),
  CONSTRAINT SAWON_6_PK PRIMARY KEY(S_NO)
);

INSERT INTO SAWON_6 VALUES(1,'신명숙',12345.678);
INSERT INTO SAWON_6 VALUES(2,'김은희',12345.6789);
INSERT INTO SAWON_6 VALUES(3,'최경녀',12345.678);
INSERT INTO SAWON_6 VALUES(4,'심봉선',12345.678);
SELECT * FROM SAWON_6;

/*
4. foreign key
*/
DROP TABLE DEPT_2;

CREATE TABLE DEPT_2(
    DEPTNO number(4) CONSTRAINT DEPT_2_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(10),
    LOC VARCHAR2(10)
);

INSERT INTO DEPT_2 VALUES(10, '인사', '서울');
INSERT INTO DEPT_2 VALUES(20, '경리', '부산');
INSERT INTO DEPT_2 VALUES(30, '관리', '대구');

SELECT * FROM DEPT_2;


DROP TABLE EMP2;
CREATE TABLE EMP2(
    EMPNO NUMBER(4) CONSTRAINT EMP2_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    SAL NUMBER(10),
    DEPTNO NUMBER(4) CONSTRAINT EMP2_DEPTNO_FK REFERENCES DEPT_2(DEPTNO) ON DELETE CASCADE
);



SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS;

INSERT INTO EMP2 VALUES(1, '사원1', 100000, 10);
INSERT INTO EMP2 VALUES(1111,'홍길동',3000,10);
INSERT INTO EMP2 VALUES(2222,'홍길서',7000,20);
INSERT INTO EMP2 VALUES(3333,'홍길남',5000,10);
INSERT INTO EMP2 VALUES(4444,'홍길북',2000,NULL);
INSERT INTO EMP2 VALUES(5555,'강감찬',6000,50);
--SQL 오류: ORA-02291: integrity constraint (SCOTT.EMP_2_DEPTNO_FK)
--                    violated - parent key not found
SELECT * FROM EMP2;

DELETE FROM DEPT_2 WHERE DEPTNO=10;
--SQL 오류: ORA-02292: integrity constraint (SCOTT.EMP_2_DEPTNO_FK) violated 
--          - child record found



/*
5. CHECK
*/

CREATE TABLE SAWON_7(
  S_NO NUMBER(2) PRIMARY KEY,
  S_NAME VARCHAR2(10),
  S_SAL NUMBER(10) CONSTRAINT SAWON_7_S_SAL_CK CHECK(S_SAL < 500)
);
SELECT CONSTRAINT_NAME,
       CONSTRAINT_TYPE,
       TABLE_NAME
FROM SYS.USER_CONSTRAINTS;

INSERT INTO SAWON_7 VALUES(1,'KIM',400);
INSERT INTO SAWON_7 VALUES(2,'JIM',300);
INSERT INTO SAWON_7 VALUES(3,'SIM',200);
COMMIT;
--INSERT INTO SAWON_7 VALUES(4,'SIM',800);
--SQL 오류: ORA-02290: check constraint (SCOTT.SAWON_7_S_SAL_CK) violated


/***************
DROP TABLE
TRUNCATE TABLE
****************/
SELECT * FROM SAWON_7;
DELETE FROM SAWON_7;
ROLLBACK;

RENAME SAWON_7 TO SAWON_77;
DESC SAWON_7;
DESC SAWON_77;
SELECT * FROM SAWON_77;

TRUNCATE TABLE SAWON_77;
ROLLBACK;

DROP TABLE SAWON_77;
/****************
    VIEW
*****************/

CREATE VIEW EMP_VIEW
AS
SELECT EMPNO,ENAME,SAL,HIREDATE
FROM EMP
WHERE DEPTNO=10;

SELECT * FROM USER_VIEWS;
SELECT * FROM (SELECT EMPNO,ENAME,SAL,HIREDATE
                FROM EMP
              WHERE DEPTNO=10);


SELECT EMPNO,ENAME,SAL,HIREDATE FROM EMP_VIEW;

CREATE OR REPLACE VIEW DEPT_VIEW
AS
SELECT DEPTNO NO ,DNAME NAME
FROM DEPT;

DESC DEPT_VIEW;

SELECT * FROM DEPT_VIEW;

CREATE OR REPLACE VIEW DEPT_VIEW
AS
SELECT DEPTNO NO,DNAME NAME ,LOC
FROM DEPT;

